name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate Terraform module
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: terraform init
        run: terraform init

      - name: validate
        run: terraform validate
